# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = 
client_id = 
application_url = "https://editors-cod-chat-brisbane.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://editors-cod-chat-brisbane.trycloudflare.com/auth/callback",
  "https://editors-cod-chat-brisbane.trycloudflare.com/auth/shopify/callback",
  "https://editors-cod-chat-brisbane.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = 
